version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  commit-message:
    prefix: chore(deps)
